import BaseAgent from "../core/BaseAgent.js";
import { StringUtils } from "../../utils/StringUtils.js";

function uniqueLocators(actions = []) {
  const map = new Map();
  for (const action of actions) {
    if (!action.locatorName || !action.selector) continue;
    if (!map.has(action.locatorName)) {
      map.set(action.locatorName, {
        name: action.locatorName,
        selector: action.selector,
        description: action.elementName || action.locatorName
      });
    }
  }
  return [...map.values()];
}

export class ArtifactDesignAgent extends BaseAgent {
  constructor(deps = {}) {
    super("ArtifactDesignAgent", deps);
  }

  async execute(_input = {}, context = {}) {
    const story = context.userStory || context.story || {};
    const navigation = context.navigation || {};
    const titleBase = StringUtils.toPascalCase(story.title || "GeneratedStory") || "GeneratedStory";
    const classBase = `Agentic${titleBase}`;
    const slug = StringUtils.sanitizeFileName(`agentic-${story.title || "generated-story"}`);
    const pageClassName = `${classBase}Page`;
    const locatorClassName = `${classBase}Locators`;
    const locators = uniqueLocators(navigation.actions);
    const supportedFlowActionTypes = new Set([
      "navigate",
      "type",
      "click",
      "hover",
      "selectOption",
      "pressKey",
      "wait",
      "navigateBack",
      "navigateForward"
    ]);

    const flowActions = (navigation.actions || []).filter((action) => supportedFlowActionTypes.has(action.type));
    const assertionAction = [...(navigation.actions || [])].reverse().find((a) => a.type === "assertVisible");
    const isLogin = /auth|login/i.test(navigation.detectedFlow || "");

    return {
      artifactId: slug,
      slug,
      featureSpec: {
        featureName: story.title || "Generated User Story",
        description: "Generated by agentic pipeline from user story + app navigation trace.",
        tags: ["@generated", "@agentic"],
        scenarioName: "Generated flow from user story",
        steps: [
          { keyword: "Given", text: "the user launches the generated application" },
          {
            keyword: "When",
            text: `the user executes generated flow using test data row "${isLogin ? "StandardUser" : "DefaultRow"}"`
          },
          { keyword: "Then", text: "the user should see the expected generated outcome" }
        ]
      },
      stepSpec: {
        pageClassName,
        launchPattern: "the user launches the generated application",
        flowPattern: "the user executes generated flow using test data row {string}",
        assertPattern: "the user should see the expected generated outcome",
        excelPath: "src/data/TestData.xlsx",
        sheetName: isLogin ? "LoginData" : "GeneratedData"
      },
      pageSpec: {
        className: pageClassName,
        locatorClassName,
        flowActions: flowActions.map((action) => ({
          type: action.type,
          locatorName: action.locatorName || null,
          valueKey: action.valueKey || null,
          elementName: action.elementName || action.description || action.type,
          selector: action.selector || action.input?.selector || null,
          url: action.input?.url || null,
          key: action.input?.key || null,
          value: action.input?.value || null,
          label: action.input?.label || null,
          waitTime: action.input?.time || null
        })),
        assertion: assertionAction?.locatorName
          ? { locatorName: assertionAction.locatorName, elementName: assertionAction.elementName }
          : { locatorName: "mainContent", elementName: "Main Content Marker" }
      },
      locatorSpec: {
        className: locatorClassName,
        entries:
          locators.length > 0
            ? locators
            : [{ name: "mainContent", selector: "main", description: "Main content region" }]
      }
    };
  }
}

export default ArtifactDesignAgent;
