import { spawnSync } from "node:child_process";
import BaseAgent from "../core/BaseAgent.js";

export class GitHubWorkflowAgent extends BaseAgent {
  constructor(deps = {}) {
    super("GitHubWorkflowAgent", deps);
  }

  async execute(_input = {}, context = {}) {
    const artifacts = context.codeMapper?.artifacts || [];
    const changedPaths = artifacts.map((a) => a.targetPath).sort();
    const ghCheck = spawnSync("gh", ["--version"], { encoding: "utf-8", shell: process.platform === "win32" });
    const ghAvailable = !ghCheck.error && ghCheck.status === 0;
    const ghVersion = ghAvailable ? (ghCheck.stdout || "").split(/\r?\n/)[0].trim() : "Not available";

    const markdown = [
      "# GitHub Publish Workflow",
      "",
      `GitHub CLI detected: ${ghAvailable ? "yes" : "no"}`,
      `Version: ${ghVersion}`,
      "",
      "## Files generated by agentic run",
      ...changedPaths.map((p) => `- \`${p}\``),
      "",
      "## CLI flow",
      "```bash",
      "git checkout -b feat/agentic-story-generated",
      "git add .",
      "git commit -m \"feat: generate automation artifacts from user story\"",
      "git push -u origin feat/agentic-story-generated",
      "gh pr create --fill --draft",
      "```",
      "",
      "## UI flow",
      "1. Open GitHub repository in browser.",
      "2. Compare the pushed feature branch to main.",
      "3. Create draft PR and include generated story evidence.",
      "4. Request review from automation owners.",
      ""
    ].join("\n");

    return {
      ghAvailable,
      ghVersion,
      changedPaths,
      markdown
    };
  }
}

export default GitHubWorkflowAgent;
