Feature: Login should support valid and invalid user outcomes
  Generated by agentic pipeline from user story + app navigation trace.

  @generated @agentic
  Scenario: Generated flow from user story
    Given the user launches the generated application
    When the user executes generated flow using test data row "StandardUser"
    Then the user should see the expected generated outcome
